// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

type AwsAccount struct {
	ID   string
	Name string
	Note string
}

type AwsAccountSystemRelation struct {
	ID           string
	AwsAccountID string
	SystemID     string
}

type AwsAccountUserRelation struct {
	ID           string
	AwsAccountID string
	UserID       string
	Role         string
}
