# .air.toml

# Working directory
root = "."
tmp_dir = "tmp"

[build]
# ビルド後のバイナリファイルの出力先
bin = "tmp/main"
# ビルドコマンド
cmd = "go build -o tmp/main ."
# リロードの遅延時間 (ミリ秒)
delay = 1000

[log]
# ログの出力先
main_log = "air.log"

# ファイル変更監視
[watcher]
full_reload = false