FROM golang:1.23-alpine

# 必要なパッケージをインストール
RUN apk add --no-cache curl git

# Airをダウンロードしてインストール
RUN go install github.com/air-verse/air@v1.61.7

# ワーキングディレクトリを設定
WORKDIR /app

# go.mod と go.sum をコピーして依存関係をインストール
COPY go.mod go.sum ./
RUN go mod download

# ソースコードと設定ファイルをコピー
COPY . ./
ENV GO_ENV development

# ホットリロードで開発用サーバを起動
CMD ["air", "-c", ".air.toml"] 