// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

type System struct {
	ID   string
	Name string
	Note string
}

type SystemUserRelation struct {
	ID       string
	SystemID string
	UserID   string
}
