# 公式SpiceDBイメージを使用
FROM authzed/spicedb:v1.44.4

# 作業ディレクトリを設定
WORKDIR /app

# SpiceDBサーバーの起動
EXPOSE 8080 50051

# serveサブコマンドから開始
CMD [ \
  "serve", \
  "--grpc-preshared-key", "spicedb-secret-key", \
  "--http-enabled", \
  "--datastore-engine", "postgres", \
  "--datastore-conn-uri", "postgres://spicedb:spicedb123@spicedb_postgres:5432/spicedb?sslmode=disable", \
  "--grpc-addr", "0.0.0.0:50051", \
  "--http-addr", "0.0.0.0:8080", \
  "--log-level", "debug" \
] 